[2024-07-13T02:08:29.621+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T02:08:29.647+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_book_api_pipeline.transform_data manual__2024-07-13T02:08:18.734580+00:00 [queued]>
[2024-07-13T02:08:29.653+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_book_api_pipeline.transform_data manual__2024-07-13T02:08:18.734580+00:00 [queued]>
[2024-07-13T02:08:29.653+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-13T02:08:29.669+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-07-13 02:08:18.734580+00:00
[2024-07-13T02:08:29.677+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=608) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-13T02:08:29.678+0000] {standard_task_runner.py:63} INFO - Started process 610 to run task
[2024-07-13T02:08:29.679+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', '***_book_api_pipeline', 'transform_data', 'manual__2024-07-13T02:08:18.734580+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/***_book_api_dags.py', '--cfg-path', '/tmp/tmpp7w1po1g']
[2024-07-13T02:08:29.679+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask transform_data
[2024-07-13T02:08:29.720+0000] {task_command.py:426} INFO - Running <TaskInstance: airflow_book_api_pipeline.transform_data manual__2024-07-13T02:08:18.734580+00:00 [running]> on host e6b306b9c204
[2024-07-13T02:08:29.795+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='zainal' AIRFLOW_CTX_DAG_ID='***_book_api_pipeline' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T02:08:18.734580+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-13T02:08:18.734580+00:00'
[2024-07-13T02:08:29.797+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T02:08:29.804+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T02:08:29.805+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_book_api_dags.py", line 18, in transform_data
    for book in book_data['works']:
                ~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-07-13T02:08:29.812+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=***_book_api_pipeline, task_id=transform_data, run_id=manual__2024-07-13T02:08:18.734580+00:00, execution_date=20240713T020818, start_date=20240713T020829, end_date=20240713T020829
[2024-07-13T02:08:29.827+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 17 for task transform_data ('NoneType' object is not subscriptable; 610)
[2024-07-13T02:08:29.851+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-13T02:08:29.869+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-13T02:08:29.876+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
